name: rspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        activerecord:
          - '4.1'
          - '5.0'
          - '6.0'
          - '6.1'
          - '7.0'
          - '8.0'
        exclude:
        # Ruby 3.1 has problem with Rails 7 currently (https://gist.github.com/yahonda/2776d8d7b6ea7045359f38c10449937b#add-classdescendants)
        - ruby: '3.1'
          activerecord: '7.0'

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Install sqlite3 on system
      run: |
        sudo apt-get install libsqlite3-dev

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name : Install dependency
      run: |
        gem install bundler
        bundle install
        gem update --system 3.3.3

    - name: Run appraisal to install different active records version
      run: |
        bundle exec appraisal install

    - name: Run rspec test across active record
      run: |
        bundle exec appraisal activerecord-${{ matrix.activerecord }} rspec

